name: Keep Replit App Alive

on:
  schedule:
    - cron: '*/1 * * * *'  # 每1分钟执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Replit App
        run: |
          curl -s -o /dev/null -w "%{http_code}" "https://workspace.qiangshao.repl.co" | grep -q "200" && echo "Ping successful" || echo "Ping failed"
        continue-on-error: true  # 即使失败也继续执行
      
      - name: Log timestamp
        run: echo "Ping executed at $(date)"
